# Generated by Django 2.2.6 on 2020-02-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='image',
            field=models.ImageField(default='portfolio_pieces/wloczykij_WIP.jpg', upload_to='portfolio_pieces/'),
        ),
    ]
